### ISSUE TITLE
Add accessory 

### ISSUE THREAD

**Issue by roberkane212** [plasticrake/homebridge-tplink-smarthome#104]
can we please add power strip icon to HS300?

**Comment by plasticrake** [comment]
I do not believe this has anything to do with home bridge or this plugin, sounds like you're referring to the home app.

**Comment by roberkane212** [comment]
No it will have to be implemented in the plugin itself

**Comment by roberkane212** [comment]
@plasticrake why did you close when you had no idea how to implement this??!!!

**Comment by roberkane212** [comment]
![](https://user-images.githubusercontent.com/44589993/71549435-34211e00-298b-11ea-9641-560ca0fe237f.jpeg)
