### ISSUE TITLE
TplinkSmarthome' was not registered by any plugin.

### ISSUE THREAD

**Issue by blantonator** [plasticrake/homebridge-tplink-smarthome#115]
Hi all.  I've installed the plugin and am receiving this error when I start homebridge.  Any help would be appreciated!

[2/8/2020, 5:38:53 PM] Loading 1 platforms...
[2/8/2020, 5:38:53 PM] Error: The requested platform 'TplinkSmarthome' was not registered by any plugin.

**Comment by Vampier** [comment]
did you install the plugin?

**Comment by blantonator** [comment]
yes, I tried reinstalling it as well.

**Comment by Kraveylicious** [comment]
Same issue, need to reinstall the plugin every time to get working again.
