### ISSUE TITLE
TP-LINK Tapo P100

### ISSUE THREAD

**Issue by Blaster681** [plasticrake/homebridge-tplink-smarthome#121]
Hi there,

Is this plug allready compatible with the plugin TP-LINK Tapo P100 ?

Thanks in advance,

**Comment by saendu** [comment]
I tried today and it was not.

**Comment by MrJosu** [comment]
Ehh unlucky, was about to buy this plug. Good what i checked, hopefully it will be supported in the near future:( I need slim smart plug for my extension lead in cable rack

**Comment by jon-daemon** [comment]
I'd also like to see that. Would that be possible in the future?

**Comment by Mightymekon** [comment]
Yes, +1 for this- they're cheap and easy to come by, it would be fantastic to have them working with Homebridge.

**Comment by PCasp** [comment]
Please please go ahead with this!
