### ISSUE TITLE
Latest version not published on npmjs

### ISSUE THREAD

**Issue by milmber** [plasticrake/homebridge-tplink-smarthome#127]
### Expected Behavior
The latest version (5.0.0) is available on npmjs on when using ‘npm update -g homebridge-tplink-smarthome’ to update

### Current Behavior
Version is 4.0.1 is available

### Steps to Reproduce (for bugs)
Check https://www.npmjs.com/package/homebridge-tplink-smarthome

### Versions
5.0.0

**Comment by mrjackyliang** [comment]
The update was pulled because of an issue.

**Comment by ronald-mendoza** [comment]
An issue with updating via npmjs, or with 5.0 itself, meaning 5.0 shouldn't be used at this time?

**Comment by ronald-mendoza** [comment]
> An issue with updating via npmjs, or with 5.0 itself, meaning 5.0 shouldn't be used at this time?



> The update was pulled because of an issue.

An issue with updating via npmjs, or with 5.0 itself, meaning 5.0 shouldn't be used at this time?

**Comment by ronald-mendoza** [comment]
> The update was pulled because of an issue.

An issue with updating via npmjs, or with 5.0 itself, meaning 5.0 shouldn't be used at this time?

**Comment by mrjackyliang** [comment]
5.0 itself.

**Comment by mshulman** [comment]
Issue #110 is marked as Closed, but there's no release with the checkin for it. @plasticrake , did you forget to do a release?

**Comment by plasticrake** [comment]
5.1.0 released
