### ISSUE TITLE
Feature Request: add plug LED state control

### ISSUE THREAD

**Issue by chrisjshull** [plasticrake/homebridge-tplink-smarthome#135]
The underlying tplink-smarthome-api library has the ability to read/control the LED state of plugs:
https://plasticrake.github.io/tplink-smarthome-api/classes/plug.html#setledstate

Can we get this added as something I can control? (Maybe opt-in.)

**Comment by plasticrake** [comment]
This could be possibly be achieved by adding a LightBulb service to the device, but I'm not sure that would be wise. If you said "Hey Siri, turn on/off all the lights" it would then turn on/off the LED. Going to close this issue, but I may be open to a pull request and have this option be disabled by default if anyone wants to do that.

**Comment by chrisjshull** [comment]
It's a good point, but could this be exposed as a custom characteristic available in (e.g.) Eve?
Can you leave this open so people can find it if they are looking for a small thing to add?
