### ISSUE TITLE
Updated to 5.2.0 , TP Link plugin broke

### ISSUE THREAD

**Issue by Fofer** [plasticrake/homebridge-tplink-smarthome#143]
Hi, I updated to 5.2.0 and my setup which was working fine no longer does.  This is what’s in my error log:

10/13/2020, 7:16:13 AM Loaded plugin "homebridge-tplink-smarthome".
10/13/2020, 7:16:13 AM The requested platform "TplinkSmarthome" was not registered by any plugin.
10/13/2020, 7:16:13 AM Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

**Comment by Fofer** [comment]
Another user experienced the same issue: https://reddit.com/r/HOOBS/comments/jacatq/dont_upgrade_tplink_smarthome_plugin_for/

Another plugin had this issue, and it was fixed recently, so perhaps a clue lies therein: https://github.com/mmende/homebridge-samsungtv-control2/issues/30

**Comment by Fofer** [comment]
I apologize, I was typing too quickly on my phone and not thinking clearly early this morning. I shouldn't have submitted this report that hastily, and I should have filled out the issue template.  Please close the issue if necessary, I can try to figure this out on my own?  In the meantime I reverted to the previous version from my backup and it's working fine again.
That said, I'm also not using homebridge. I am using [HOOBS](https://hoobs.org)

I have been using this excellent plugin for months without any issue, as listed as "certified" on the HOOBS page.
https://plugins.hoobs.org/plugin/homebridge-tplink-smarthome

This does seem to be an issue for other homebridge plugins, so hopefully this information can help others out there.
https://github.com/mmende/homebridge-samsungtv-control2/issues/22

**Comment by plasticrake** [comment]
My guess is you're using (or HOOBS is using) Homebridge < v1.0.0. The fix you linked was to change to code to work with older versions of Homebridge which I don't plan on doing. There are other things in this plugin that may not work on older versions as well. I may bump the version to v6.0.0 as this was a breaking change. Let me know what you find out on your version

**Comment by Fofer** [comment]
Yes you are 100% correct.    In the meantime I simply uninstalled and reinstalled 5.1.0 and its working fine.  The HOOBS devs have pulled 5.2.0 from their plugin directory and reverted to 5.1.0, they said they will reinstate the new version after an impending HOOBS update, which I suspect will be incorporating the newest version of Homebridge. 

https://old.reddit.com/r/HOOBS/comments/jacatq/dont_upgrade_tplink_smarthome_plugin_for/g8p3lnr/

**Comment by plasticrake** [comment]
I'm not familiar with HOOBS but you may want to ask them to use the version information inside the plugin's package.json to determine eligible plugins. For example in this package.json:

```json
  "engines": {
    "homebridge": ">=1.1.0",
    "node": ">=10.17.0"
  }
```

**Comment by Fofer** [comment]
Thanks, I passed that note along.
