### ISSUE TITLE
After Update All my TP-Link devices had gone

### ISSUE THREAD

**Issue by izkorn** [plasticrake/homebridge-tplink-smarthome#145]
Hi,

After I update the plugin in Hoobs, all my TP-link devices is gone. I have to uninstall and install back the plugin. Only after that I can see back the device.

### Versions

- **Node**:       `node --version`
- **Homebridge**: `homebridge --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by plasticrake** [comment]
Please fill out the issue template next time. I assume you're running an older version of homebridge which is not supported. >= v1.1.0 is required
