### ISSUE TITLE
fireCharacteristicUpdateCallback [false]: Unable to call updateCallback OutletInUse

### ISSUE THREAD

**Issue by ShahrumAmiri** [plasticrake/homebridge-tplink-smarthome#146]
Hello,

Since 6.0.0, I am getting "fireCharacteristicUpdateCallback [false]: Unable to call updateCallback OutletInUse" errors for all of my Smart Switches. They seem to be controller just fine, despite this warning. Any ideas what could be causing this?

**Comment by plasticrake** [comment]
Closing since the issue template was not filled out. Please reopen a issue with details so I can investigate. Thanks

**Comment by plasticrake** [comment]
@ShahrumAmiri Was able to figure this out, will be fixed in an upcoming version, thanks!
