### ISSUE TITLE
The requested platform "TplinkSmarthome" was not registered by any plugin

### ISSUE THREAD

**Issue by mcalderin** [plasticrake/homebridge-tplink-smarthome#147]
Receiving this error on HOOBS after installing.  As a result, no devices are detected.

10/17/2020, 11:37:19 AM Loaded plugin "homebridge-tplink-smarthome".
10/17/2020, 11:37:19 AM The requested platform "TplinkSmarthome" was not registered by any plugin.
10/17/2020, 11:37:19 AM Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

node 12.16.3
hoobs 3.2.6

        {
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ]
        }

**Comment by plasticrake** [comment]
I'm assuming you're running an older unsupported version of homebridge. From the README: Homebridge v1.1.0 or greater is required. Check by running `homebridge --version`

**Comment by Fofer** [comment]
It's a HOOBS issue indeed, the HOOBS dev team should address this:  https://old.reddit.com/r/HOOBS/comments/jacatq/dont_upgrade_tplink_smarthome_plugin_for/

**Comment by mcalderin** [comment]
Thanks!
