### ISSUE TITLE
HS100 not working on any update after v5.1.0

### ISSUE THREAD

**Issue by marioPS** [plasticrake/homebridge-tplink-smarthome#148]
### Expected Behavior

HS100's work exceptionally fine on v5.1.0

Upgrading to later versions (as at 20/10/2020) cause device to not be able to be controlled by Homekit
### Current Behavior

Upgrades to plug in broke ability to change status in Homekit, but still work if toggled by Homebridge 'Appliances' tab.

### Steps to Reproduce (for bugs)

Upgrading breaks it
Downgrading to v5.1.0 fixes it.
### Versions

- **Node**:       `node --version` v12.18.3 
- **Homebridge**: `homebridge --
version` v1.3.0-beta.12
('upgraded to beta to  see if it fixed - it didn't)
- **OS**:          MacOS 10.9.5

### Configuration

```json
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
```

### Homebridge Log / Command Output

```
This line appears when broken:
[Tplink Smarthome] set Value: Invalid On: 0
```

**Comment by plasticrake** [comment]
Please provide your homebridge version as requested

**Comment by marioPS** [comment]
@plasticrake Done.

**Comment by plasticrake** [comment]
There are changes in the beta that are not compatible with this version of the plugin. You'll have to use the latest non-beta release of homebridge.

**Comment by plasticrake** [comment]
I just re-read, you also ran this on version 1.1.6 of homebridge and has the same issue?

**Comment by marioPS** [comment]
Yes. I'll roll back HB and install latest plugin and confirm.
If fails, will roll back again to v5.1.0.
Wish me luck!

**Comment by marioPS** [comment]
HB: 1.2.3
Plugin: 6.0.1
All working OK now.
Thanks for your advice!
