### ISSUE TITLE
homebridge-tplink-smarthome 6.1.0 error

### ISSUE THREAD

**Issue by recoi1er** [plasticrake/homebridge-tplink-smarthome#149]
homebridge-tplink-smarthome 6.1.0 error

### Expected Behavior
Not error out and work?

### Current Behavior
Filled out config for the plugin and nothing happens, log shows:

- The requested platform "TplinkSmarthome" was not registered by any plugin.
- Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.

### Steps to Reproduce (for bugs)
Install plugin, setup the config and it doesnt work. Log shows errors that were present in the 6.0.0 version as well: https://github.com/hoobs-org/HOOBS/issues/850

### Versions

- **Node**:       12.16.3
- **Homebridge**: 3.2.6
- **OS**:         HOOBS

### Configuration

```

platform | "TplinkSmarthome"
-- | --
plugin_map |  
plugin_name | "homebridge-tplink-smarthome"
name | "TplinkSmarthome"
addCustomCharacteristics | false
deviceTypes |  
0 | "plug"
1 | "bulb"
switchModels |  
0 | "HS100"
1 | "KP400"
broadcast | "255.255.255.0"
pollingInterval | 30
transport | "tcp"
timeout | 15
waitTimeUpdate | 100


```

### Homebridge Log / Command Output

```
10/21/2020, 3:26:30 PM Got SIGINT, shutting down Bridge...
10/21/2020, 3:26:34 PM Loaded plugin "homebridge-tplink-smarthome".
10/21/2020, 3:26:35 PM The requested platform "TplinkSmarthome" was not registered by any plugin.
10/21/2020, 3:26:35 PM Your config.json is requesting the platform "TplinkSmarthome" which has not been published by any installed plugins.
10/21/2020, 3:26:35 PM Bridge is running on port 51826.
```

**Comment by plasticrake** [comment]
Closing, dupe #147. Please upgrade your homebridge or use an older version of this plugin

**Comment by recoi1er** [comment]
I upgraded and still doesn’t work, logs changed with no errors but nothing showing up. Is my config correct?

**Comment by plasticrake** [comment]
Why do your logs start with "shutting down Bridge"? Can you post full logs?

**Comment by plasticrake** [comment]
Your broadcast address looks suspect, why don't you use the default? I can't really support HOOBS

**Comment by recoi1er** [comment]
For the broadcast address, that was left over from me trying different things to get this work and forgot to roll it back to defaults but that fixed it. Working now, thanks!
