### ISSUE TITLE
HS100 & HS110 turn on randomly

### ISSUE THREAD

**Issue by gongevangen** [plasticrake/homebridge-tplink-smarthome#150]
### Expected Behavior
I have 1 HS100 and 2 HS110 that I use to control some Christmas lightning. I have reset all HS1x0 so I am sure the is no timers on the units themself. In the HomeKit app I have made 4 timers: turn on at 5:00, turn off at sunrise, turn on at sunset and turn off at 22:00. 

### Current Behavior
I all works nicely except that sometime during the night between 22:00 and and 5:00 (where the switches should be off) they turn on. I don't know the exact time, because I am sleeping. 

### Steps to Reproduce (for bugs)
Setup 3 HS1x0 as described above.

### Versions

- **Node**:       12.18.3
- **Homebridge**: 1.2.2
- **OS**:         NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

### Configuration

```json
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        }
```

### Homebridge Log / Command Output
There is no interesting log output

```

```

**Comment by plasticrake** [comment]
I doubt this has anything to do with this plugin. You can try running homebridge with debug mode on and see if there is anything in the logs around that time.
