### ISSUE TITLE
Support for TP-Link KP105P2

### ISSUE THREAD

**Issue by jostrasser** [plasticrake/homebridge-tplink-smarthome#157]
Hi,

will the plugin work also with a TP-Link KP105P2 device?

Thanks!

**Comment by jamesrodda** [comment]
I’ve just bought a couple of these today (just KP105 though - I assume the “P2” is a 2 pack identifier?) and they work absolutely flawlessly. Plugged in, setup via the Kasa app, opened the Home app and it was there ready and waiting.

Got a few HAP warnings re some unexpected characteristics (they look to be related to wattage/voltage/etc) but it handles them fine. I can provide the uuids if needed.

**Comment by jostrasser** [comment]
@jamesrodda thanks for your information!

Yes, U're right, P2 = 2-Pack. Sorry ;)
