### ISSUE TITLE
Does this support the newer KL130 and KL110 Light bulbs?

### ISSUE THREAD

**Issue by raidalgman** [plasticrake/homebridge-tplink-smarthome#158]
### Current Behavior

 Does this support the newer KL130 and KL110 Light bulbs?

### Versions

- **Node**:       `node --version`
- **Homebridge**: `homebridge --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by plasticrake** [comment]
Probably! Let us know.

**Comment by EduardJedna** [comment]
I have this working with a KL110 light bulb.

![KL110](https://user-images.githubusercontent.com/76907816/103480157-9f70ad80-4da0-11eb-9c49-36b489258cc4.jpg)
