### ISSUE TITLE
HS200 Firmware appears to break funcstion of the switch

### ISSUE THREAD

**Issue by death-of-the-party** [plasticrake/homebridge-tplink-smarthome#169]
Appears that the 1.1.4 firmware have broken the switch function.  
### Expected Behavior

Should work
### Current Behavior

Homekit/homebridge shows it activating but the switch does nothing.
### Versions

- **Node**:       `14.15.1 `
- **Homebridge**: `homebridge-rpi v1.2.7 
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by SilentStorm16** [comment]
I am having the same issue.  I have the HS200, HS220, and HS105 plugs and all of them are not responding within Homekit.  They all show up, I click on to turn on the switch and homekit says its on, but the light is not.  This is what is in my configuration file.  Thanks in advance.

 "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "switchModels": [
                "HS200",
                "HS220",
                "HS105"

**Comment by plasticrake** [comment]
Closing due to issue template not being filled out
