### ISSUE TITLE
Can't remove accessory from Homebridge

### ISSUE THREAD

**Issue by SnapdGIT** [plasticrake/homebridge-tplink-smarthome#171]
Hello,

Sorry if this is a stupid question.

I've been using this plugin for ages without issue but was forced to reinstall Homebridge from scratch a couple of days ago. Thanks to that I've discovered the Homebridge Config UI and have updated all the plugins using that. Homebridge is now running as a service, rather than being manually run from a MacOS Terminal window.

I've stopped using a TPLink smart plug but I can't seem to remove it from Homebridge. Before I'd updated to remove a TPLink item I'd delete its details from the cachedAccessories file and stop and restart Homebridge and it would be gone.

Now if I edit the file and then restart Homebridge it's been re-added to the cachedAccessories file.

Apologies if I'm missing a simple step, any help would be appreciated.

Tplink Smarthome v6.1.0

**Comment by tr1ng0** [comment]
@SnapdGIT did you try removing it via the homebridge-ui homebridge Settings? Not sure how the function is called in Englisch but you will find it searching for something like delete single device from cache (I don not mean touching the cachedAccessories file)

**Comment by SnapdGIT** [comment]
Thanks. That solved the problem.
Here's the link if anyone else is looking for this answer: https://github.com/oznu/homebridge-config-ui-x/issues/525

**Comment by tr1ng0** [comment]
@SnapdGIT your welcome :) 
@plasticrake  i believe this issue can be closed
