### ISSUE TITLE
Support for Kasa Scenes?

### ISSUE THREAD

**Issue by adjoseph16** [plasticrake/homebridge-tplink-smarthome#175]
Hey there!

Awesome plugin - super simple to get set up and it works like a charm. I had one question though: All of my Kasa devices ported over automatically, but none of my Kasa scenes did. Is there any way to get those into Homebridge? I don’t mind if I need to make some manual changes to the config file.

Trying to get Google Home and Siri on the same page device-wise :)

Thank you!

**Comment by plasticrake** [comment]
Homebridge is only to expose devices, it does not handle scenes
