### ISSUE TITLE
Warnings on optional characteristics..

### ISSUE THREAD

**Issue by scottjl** [plasticrake/homebridge-tplink-smarthome#201]
New installation of plugin for new Kasa HS103 outlet, which do not have monitoring. Receiving the following warnings for each outlet:

> [5/26/2021, 12:02:30 PM] [TplinkSmarthome] New Device Online: [Pinball] plug [redacted] redacted 9999
> [5/26/2021, 12:02:30 PM] [TplinkSmarthome] Adding: [Pinball] plug [redacted]
> [5/26/2021, 12:02:30 PM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Amperes': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
> [5/26/2021, 12:02:30 PM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Total Consumption': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
> [5/26/2021, 12:02:30 PM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Apparent Power': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
> [5/26/2021, 12:02:30 PM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Volts': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.
> [5/26/2021, 12:02:30 PM] [homebridge-tplink-smarthome] This plugin generated a warning from the characteristic 'Consumption': Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.. See https://git.io/JtMGR for more info.

Unchecking "Adds energy monitoring characteristics.." in plugin settings > homekit removed the error messages.

**Comment by plasticrake** [comment]
You did not provide your config or any version info from the template. I have a feeling you have a config issue, if you post it someone can help.

**Comment by scottjl** [comment]
sorry.. nothing fancy here. if you need the whole file let me know. but i took just the default settings for the plugin, except for that one checkbox.

> {
>             "name": "TplinkSmarthome",
>             "addCustomCharacteristics": false,
>             "deviceTypes": [
>                 "plug"
>             ],
>             "platform": "TplinkSmarthome"
>         }
>     ],
