### ISSUE TITLE
HS220 Brightness not working

### ISSUE THREAD

**Issue by megibow** [plasticrake/homebridge-tplink-smarthome#203]
### Current Behavior
HS220 Dimmer Switch shows up as just an on/off switch, so no ability to set brightness.

In the log, for each HS220, getting a ton of the following messages:
`fireCharacteristicUpdateCallback [Brightness]: Unable to call updateCallback`

### Versions

- **Node**:       `v14.16.0`
- **Hoobs**: `3.3.5`
- **OS**:        `Raspbian GNU/Linux, Release 10, Kernel 5.10.11-v7l+`

### Configuration

```        
{
            "platform": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            },
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "switchModels": [
                "HS100",
                "HS103",
                "HS200",
                "HS210",
                "HS220"
            ],
            "transport": "tcp",
            "waitTimeUpdate": 100,
            "macAddresses": [],
            "excludeMacAddresses": [],
            "devices": []
        }

```

**Comment by plasticrake** [comment]
As shown on the table in the Readme, switches only support ON. That is a homekit thing. You don't have to have it as a switch though. Just remove it from switchModels and it will behave how you want (which would have been the default behavior).

**Comment by loganfernandes** [comment]
@plasticrake This fixed the issue for me in my new post. I'll update over there as well.
