### ISSUE TITLE
HS220 Dimmers No Longer Working

### ISSUE THREAD

**Issue by budliter** [plasticrake/homebridge-tplink-smarthome#204]
Recently my HS220 dimmers stopped working through homebridge.  They work fine using the KASA app, they are showing up in my homekit, but both buttons in homekit and homebridge web interface do not do anything.  

Any thoughts?

**Comment by plasticrake** [comment]
You didn't fill out the issue template so its hard to see what's wrong. But I'm going to assume you changed the switchModels config option. Please remove it.
