### ISSUE TITLE
plugin won't start on hoops

### ISSUE THREAD

**Issue by Akury83** [plasticrake/homebridge-tplink-smarthome#210]
### Expected Behavior
it should start

### Current Behavior
does not start

### Steps to Reproduce (for bugs)
try starting

### Versions
Hoobs 4.0.72, plugin ver 6.4.0

### Configuration

```

{
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome"
        }
    ]
}

```

### Homebridge Log / Command Output

```
07/07/2021, 6:13:58 pmtplinksmarthomebridge stopping
07/07/2021, 6:14:02 pmTplink Smarthome Bridge starting
07/07/2021, 6:14:06 pmTplink Smarthome BridgeLoaded plugin 'homebridge-tplink-smarthome'
07/07/2021, 6:14:06 pmTplink Smarthome BridgeLoading 1 platforms...
07/07/2021, 6:14:06 pmTplink Smarthome BridgeTplinkSmarthomehomebridge-tplink-smarthome v6.4.0, node v14.17.2, homebridge v1.3.4, api v2.7
07/07/2021, 6:14:06 pmTplink Smarthome BridgeWARNINGunhandled rejection: ConfigParseError: Error parsing config:
`` must have required property 'name'
```

**Comment by Akury83** [comment]
figured it out from other people's config

**Comment by doughnet** [comment]
> figured it out from other people's config

What was the solution?  I seem to be having the same issue.  Helps to explain the solution.

**Comment by Akury83** [comment]
All you have to do is give the bridge a name, and it does the rest. My configuration is literally as follows and it started working:

{
    "accessories": [],
    "platforms": [
        {
            "name": "TplinkSmarthome",
            "platform": "TplinkSmarthome"
        }
    ]
}

It helps if you assign the tp-link devices static IPs in your router or DHCP server.

**Comment by doughnet** [comment]
> All you have to do is give the bridge a name, and it does the rest. My configuration is literally as follows and it started working:
> 
> {
> "accessories": [],
> "platforms": [
> {
> "name": "TplinkSmarthome",
> "platform": "TplinkSmarthome"
> }
> ]
> }
> 
> It helps if you assign the tp-link devices static IPs in your router or DHCP server.

Thank you.  Seems like a super simple fix.  Wonder why the creator hasn't fixed it ...
