### ISSUE TITLE
Support for Light Strip KL400

### ISSUE THREAD

**Issue by Svision** [plasticrake/homebridge-tplink-smarthome#222]
The light strip should in the Home app with correct status but cannot control it. Showed 'no response' every time.

**Comment by Tom-Enns** [comment]
I have the same issue, from the logs it looks like it finds the light strip and even adds it to homekit as a color changeable light. but it doesnt know how to control it here is the error message that comes through: 
`[TplinkSmarthome] [Office Door Accent Lights] {"response":"{\"err_code\":-2001,\"err_msg\":\"module not support\"}","command":"{\"smartlife.iot.smartbulb.lightingservice\":{\"get_light_state\":{}}}","modules":["smartlife.iot.smartbulb.lightingservice"],"methods":[],"name":"ResponseError"}`

**Comment by rotaflex** [comment]
It would be great if KL430 could be included.

**Comment by joesarkis** [comment]
Any updated on this issue?

**Comment by Svision** [comment]
Nope, so I switched to Home Assistant which supports natively.

**Comment by joesarkis** [comment]
I'll give that a try. It's weird that no one is addressing this issue

**Comment by lhcavalcanti** [comment]
Any news on it?

**Comment by plasticrake** [comment]
Support was added in version 7 of this plugin. Tested on KL430, I would hope KL400 would work too. See #113
