### ISSUE TITLE
Hs220 not working

### ISSUE THREAD

**Issue by sfortinr** [plasticrake/homebridge-tplink-smarthome#227]
There's an issue with the HS220 that is not working without any logs. The other Kasa switch work perfectly. Cleared the accessories in cache tried to assign the right ip and the switch do nothing in HomeKit but work in Kasa app

**Comment by sfortinr** [comment]
![56568C23-F82C-4C2C-9221-45CC0AF09A92](https://user-images.githubusercontent.com/55406643/144347996-9cecea3c-b512-4229-aaee-221bd4d02326.png)

**Comment by Mongorlio** [comment]
Same issue for me. Only my one HS220 is giving me problems. All other switches and plugs have no issue.

**Comment by Mongorlio** [comment]
I have noticed that if I reset the HS220 dimmer switch, it works in homekit for a while after resetting h homebridge as well. After a while though, it just stops responding in homekit altogether. Homekit thinks it is working but no commands are received by the switch. During this it continues to work without issue in the Kasa app. @plasticrake

**Comment by plasticrake** [comment]
You didn't fill out the issue template so its hard to see what's wrong. But I'm going to assume you changed the `switchModels` config option. Please remove it.
