### ISSUE TITLE
Any plans for KC420WS support?

### ISSUE THREAD

**Issue by cbp68** [plasticrake/homebridge-tplink-smarthome#228]
Longshot, but any plans to add in support for:
Model: KC420WS (outdoor camera)
HW Ver: 1.0
FW Ver: 2.3.12

With Plugin:
homebridge-tplink-smarthome v6.4.0 (2021-05-07)

Thanks
Chris

**Comment by plasticrake** [comment]
No plans for camera support. If it supports RTSP you can use homebridge plugins that support that
