### ISSUE TITLE
Remove Accessory?

### ISSUE THREAD

**Issue by nickv2002** [plasticrake/homebridge-tplink-smarthome#230]
Dumb question but I took a TP-Link accessory out of my setup but it still shows in Homebridge. How do I delete it so it doesn't show there or in Home.app anymore?

Using `homebridge-tplink-smarthome v6.4.0` FWIW.

Thanks for your help!

**Comment by davidscholtz** [comment]
Also have this problem/question

**Comment by stangmatt66** [comment]
Same issue. I've removed a bunch of accessories from the TP-Link Kasa app, but they still appear in Homebridge. 

Using homebridge-tplink-smarthome v4.0.1 b/c anything newer causes my devices to not respond.

**Comment by nickv2002** [comment]
I figured out how to do this using the Homebridge UI (`homebridge-config-ui-x v4.41.5`). In the top right `…` menu choose *Homebridge Settings* and on that page you can click *Remove Single Cached Accessory* to get a list of accessories. Easy but buried in the settings. 😄

**Comment by nickv2002** [comment]
My previous tip about _Remove Single Cached Accessory_ didn't work for the Christmas light this year. Had to `rm -rf ~/.homebridge/accessories` (after making a backup).
