### ISSUE TITLE
Slow to respond error in HOOBS, Kasa/TpLink Switches

### ISSUE THREAD

**Issue by dSwagler** [plasticrake/homebridge-tplink-smarthome#241]
It takes approximately 5 seconds for the device to respond when controlled via iPhone on the same 1000Gb network as HOOBS Pi4B box (fresh install). Each time the device is turned on manually, it seems to "discover" the device even though they have all been added previously and in Apple Homekit already. In addition, I keep getting the following error code every time. Not all devices throw this code, but most do.

> 11:19:41 PMTplink Smarthome BridgeTplinkSmarthomeNew Device Online: [TP-LINK_Smart Dimmer_710F] plug [800652B29ED9AFE3C50EAF3D7B7E23401D1F53D8] 192.168.1.83 9999
> 
> 11:19:41 PMTplink Smarthome BridgeTplinkSmarthomeAdding: [TP-LINK_Smart Dimmer_710F] plug [800652B29ED9AFE3C50EAF3D7B7E23401D1F53D8]
> 
> 11:19:41 PMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@TP-LINK_Smart Dimmer_710F@TP-LINK_Smart Dimmer_710F@Consumption] Characteristic not in required or optional characteristic section for service Lightbulb. Adding anyway.
> 
> 11:19:41 PMTplink Smarthome BridgeTplinkSmarthomeNew Device Online: [Kitchen Lights - Slave] plug [8006F72303DC10CB56E83DCD9CB521A21D0ED4EF] 192.168.1.90 9999
> 
> 11:19:41 PMTplink Smarthome BridgeTplinkSmarthomeAdding: [Kitchen Lights - Slave] plug [8006F72303DC10CB56E83DCD9CB521A21D0ED4EF]
> 
> 11:30:40 AMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@On] The write handler for the characteristic 'On' on the accessory 'Kitchen Lights' was slow to respond!
> 
> 11:30:46 AMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@On] The write handler for the characteristic 'On' on the accessory 'Kitchen Lights' didn't respond at all!. Please check that you properly call the callback!
> 
> 12:05:47 PMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@On] The write handler for the characteristic 'On' on the accessory 'Flex Room Lights' was slow to respond!
> 
> 12:05:51 PMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@On] The write handler for the characteristic 'On' on the accessory 'Flex Room Lights' was slow to respond!
> 
> 12:05:51 PMTplink Smarthome BridgeError[Tplink Smarthome Bridge D5D4@Brightness] The write handler for the characteristic 'Brightness' on the accessory 'Flex Room Lights' was slow to respond!

I have no custom setup or configuration, running the most up to date code both on HOOBS, Pi4B, and Tp-Link plugin.

**Comment by 3ne** [comment]
Would you consider switching to Homebridge? I say this because I was an avid HOOBS user but had issues with plugins too often, this was one of them. Since switching to Homebridge the plugs are responsive as ever.

**Comment by Fofer** [comment]
I agree with 3ne.  Everything, across the board, improved when I switched from HOOBS to Homebridge, using the exact same hardware.  Plugin compatibility, reliability, and responsiveness.  I regret wasting as much time with HOOBS as I did.   And migration is easy: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge

**Comment by plasticrake** [comment]
Closing due to lack of information - issue template was not filled out. Please create a new issue and fill out the template if you'd like help. Although I do not recommend using HOOBS
