### ISSUE TITLE
Request: Support for KL135 bulb

### ISSUE THREAD

**Issue by Cramster** [plasticrake/homebridge-tplink-smarthome#262]
### Current Situation

Hi, I just loaded up your homebridge plugin, works well! I have 2 standard plugs that worked out of the box with your plugin, but I have one bulb - KL135 - which isn’t listed in the compatibility list, but perhaps in the future? :-) Much thanks and appreciation for your work!

### Proposed Change

Support KL135 bulb model

**Comment by asimcard** [comment]
This light bulb works for me. What issues are you experiencing? I just got it but sometimes after a power loss it takes a couple minutes to get responsive in HomeKit

**Comment by Cramster** [comment]
It does seem to be working now, thanks!
