### ISSUE TITLE
Will this still work after the Kasa Smarthome cloud shuts down at the end of the year?

### ISSUE THREAD

**Issue by kskenyon** [plasticrake/homebridge-tplink-smarthome#293]
### Current Situation

Cloud shutting down. Devices abandoned by Kasa.

### Proposed Change

Also, if it still works will it be possible to add the water sensor to the supported items?  Could just appear as a switch.

**Comment by plasticrake** [comment]
This does not use cloud at all. It also does not support Tapo devices

**Comment by kskenyon** [comment]
Thanks for the quick response.  I assume Tapo means a water sensor type device.  Must have a different architecture.

**Comment by plasticrake** [comment]
You weren't specific but a search found this which I assumed you were referring to: https://www.tp-link.com/us/smart-home/smart-sensor/tapo-t300/

**Comment by kskenyon** [comment]
Nope DCH-S160 Water Sensor.  A few years old but saved me a couple of times from disaster.  The one time I wasn’t there for a day and the basement had 43” of water in it.  Bummer.  Well water line broke in the wall.

K

￼

**Comment by plasticrake** [comment]
That's a D-Link product, not TP-Link

**Comment by kskenyon** [comment]
Ooops,  thanks.

K
