### ISSUE TITLE
Tplinksmartphone not working

### ISSUE THREAD

**Issue by Peltier36** [plasticrake/homebridge-tplink-smarthome#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

downloaded the app and i keep getting this error message... attempted to download older versions with the same issue. 

4/24/2023, 5:18:43 PMtplinksmarthomebridge stopping
4/24/2023, 5:19:35 PMTplink Smarthome Bridge starting
4/24/2023, 5:19:51 PMTplink Smarthome BridgeLoaded plugin 'homebridge-tplink-smarthome'
4/24/2023, 5:19:51 PMTplink Smarthome BridgeLoading 1 platforms...
4/24/2023, 5:19:51 PMTplink Smarthome BridgeTplinkSmarthomehomebridge-tplink-smarthome v7.0.0, node v16.19.1, homebridge v1.6.0, api v2.7
4/24/2023, 5:19:52 PMTplink Smarthome BridgeWARNINGunhandled rejection: ConfigParseError: Error parsing config:
`` must have required property 'name'

### What, if anything, has recently changed?

new setup

### Version

7.0.1

### Node Version

NA

### Homebridge Version

NA

### Which OS/Platform?

Other (Please describe)

### Relevant log output

```shell
4/24/2023, 5:18:43 PMtplinksmarthomebridge stopping
4/24/2023, 5:19:35 PMTplink Smarthome Bridge starting
4/24/2023, 5:19:51 PMTplink Smarthome BridgeLoaded plugin 'homebridge-tplink-smarthome'
4/24/2023, 5:19:51 PMTplink Smarthome BridgeLoading 1 platforms...
4/24/2023, 5:19:51 PMTplink Smarthome BridgeTplinkSmarthomehomebridge-tplink-smarthome v7.0.0, node v16.19.1, homebridge v1.6.0, api v2.7
4/24/2023, 5:19:52 PMTplink Smarthome BridgeWARNINGunhandled rejection: ConfigParseError: Error parsing config:
`` must have required property 'name'
```

### Configuration

```json
through HOOBs.
```

**Comment by plasticrake** [comment]
Your config is incorrect. But I do not use HOOBs and I can not support it.
