### ISSUE TITLE
Any version above 7.0.1 dimmer switches stop working

### ISSUE THREAD

**Issue by Papa-pp** [plasticrake/homebridge-tplink-smarthome#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Anything above 7.0.1 dimmer switches stop responding.

### What, if anything, has recently changed?

No response from dimmer switches

### Version

8

### Node Version

20.9.0

### Homebridge Version

latest

### Which OS/Platform?

Windows

### Relevant log output

```shell
?
```

### Configuration

```json
?
```

**Comment by timleeds15** [comment]
Same problem here. My HS220 switches are useless now in the home app. I also noticed that all the switches got split into 2? Now it shows a light AND an outlet? Only the light works

**Comment by plasticrake** [comment]
Duplicate #320
