### ISSUE TITLE
HS220 dimmer shows as switch and cannot be dimmed in HomeKit

### ISSUE THREAD

**Issue by alexsannikov** [plasticrake/homebridge-tplink-smarthome#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Since don't know when, just noticed now, my smart dimmers HS220 v3.0 hardware, v1.0.10 firmware started to become regular switches instead of dimmers in Apple Homekit.
I don't experience any problems in vendor's Kasa application, and I can change the light level in application. 
However, in Apple Homekit the switch has only toggle "On/Off", and not the light level.
I tried to google any mention or similar topics in Internet, but no luck.
If that's known issue outside of tplink-smarthome plugin, please share the necessary links, close this ticket, and accept my apologies. 

### What, if anything, has recently changed?

Just updates of Homebridge's all parts (with Node.js) to the recent versions. iOS 17.4.1.

### Version

8.0.3

### Node Version

20.12.2

### Homebridge Version

1.8.1

### Which OS/Platform?

Docker (Linux)

### Relevant log output

```shell
No logs, just UI controls (buttons/toggles)
```

### Configuration

```json
{
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "switchModels": [
                "HS220",
                "HS200",
                "HS210"
            ],
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "transport": "tcp",
            "devicesUseDiscoveryPort": false,
            "platform": "TplinkSmarthome",
            "_bridge": {
                "username": "--:--:--:--:--:--",
                "port": 48581
            }
        },
```

**Comment by plasticrake** [comment]
Remove the `switchModels` from your config 😄

**Comment by alexsannikov** [comment]
> Remove the `switchModels` from your config 😄

You are rock! Thanks a lot!!!

**Comment by alexsannikov** [comment]
Solution provided by @plasticrake. Huge thanks!
