### ISSUE TITLE
Question: Has anyone tried the new TP-LINK Smart Plug/Wifi Extenders (RE370K & RE270K)

### ISSUE THREAD

**Issue by peros550** [plasticrake/homebridge-tplink-smarthome#48]
I'm sorry, I know this is not an issue, I just didn't know where to post this question. 

I am curious if this plugin would support the newest smart plugs of TP LINK ( RE370K & RE270K) .

If anyone has tried , please let us know.  

Thank you

**Comment by plasticrake** [comment]
I don't have those devices to test myself, but from what I can tell they are setup very differently from the other devices. This feature would need to be added to the API repo.

plasticrake/tplink-smarthome-api#15
