### ISSUE TITLE
HomeBridge crashes when connection to HS110 fails

### ISSUE THREAD

**Issue by maisun** [plasticrake/homebridge-tplink-smarthome#51]
Connection to HS110 fails can cause HomeBridge crash. 
I haven't figure out why HomeBridge loses connection to HS110 and it's the first time it happens. After docker restarts the image it works fine so far.

### Expected Behavior
Maybe catch the error and try again?

### Current Behavior
HomeBridge crashes.  

### Versions
Running in Docker, how to check the versions? 

### Configuration
 {
         "platform":"Hs100"
  }

### Homebridge Log / Command Output
{"log":"/usr/local/lib/node_modules/homebridge-hs100/node_modules/hs100-api/lib/client.js:287\n","stream":"stderr","time":"2018-01-13T07:36:44.811057541Z"}
{"log":"          throw err;\n","stream":"stderr","time":"2018-01-13T07:36:44.811108025Z"}
{"log":"          ^\n","stream":"stderr","time":"2018-01-13T07:36:44.811134293Z"}
{"log":"\n","stream":"stderr","time":"2018-01-13T07:36:44.811153013Z"}
{"log":"Error: connect EHOSTUNREACH 192.168.1.127:9999\n","stream":"stderr","time":"2018-01-13T07:36:44.811171265Z"}
{"log":"    at Object._errnoException (util.js:1041:11)\n","stream":"stderr","time":"2018-01-13T07:36:44.811189565Z"}
{"log":"    at _exceptionWithHostPort (util.js:1064:20)\n","stream":"stderr","time":"2018-01-13T07:36:44.811222685Z"}
{"log":"    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)\n","stream":"stderr","time":"2018-01-13T07:36:44.811241765Z"}
```

```

**Comment by plasticrake** [comment]
Hi @maisun, I need to know the version of Node, Homebridge, and this plugin that you're using. I also need a more readable log file, and I need more context for it.

I've done testing by removing the plugs from the wall and it causes errors like that, but it doesn't crash homebridge and they start working again as soon as I plug them in. So I'm not sure what's going on.

**Comment by maisun** [comment]
Hi, thank you for looking into it! I'm running HomeBridge through docker and I'm not very technical so couldn't figure out the versions. I did the same test as you (remove the plug), and this time it didn't crash HomeBridge. It is strange but looks like a false alarm. Sorry for it!
