### ISSUE TITLE
Unable to find HS100

### ISSUE THREAD

**Issue by dephanix** [plasticrake/homebridge-tplink-smarthome#56]
Hello,

My plug works well with the Kasa app on my iPhone but i can't find it using Homebridge.

The Home app finds Homebridge but no accessory.

Could it be a problem with my config?
Thanks for your help.

{
    "bridge": {
        "name": "Homebridge",
        "username": "removed",
        "port": 51826,
        "pin": "removed"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "broadcast": "255.255.255.255",
            "devices": [],
            "deviceTypes": [
                "plug"
            ],
            "macAddresses": [
                "removed"
            ],
            "pollingInterval": 10,
            "addCustomCharacteristics": true,
            "inUseThreshold": 0,
            "switchModels": [
                "HS100"
            ],
            "timeout": 5
        }
    ]
}

**Comment by dephanix** [comment]
Yes, changed my config to 

> {
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
        }
    ]
}

> 

Yet all I get when adding on Home is this:
![fullsizeoutput_cdd](https://user-images.githubusercontent.com/37599649/37696952-d99f0bca-2cd1-11e8-974e-6090f73abe7c.jpeg)
![fullsizeoutput_cdc](https://user-images.githubusercontent.com/37599649/37696953-d9bbe466-2cd1-11e8-815e-25a9485f132b.jpeg)
![fullsizeoutput_cde](https://user-images.githubusercontent.com/37599649/37696954-d9d4f352-2cd1-11e8-853f-c5c6779eeb2c.jpeg)

**Comment by Eloquite** [comment]
Same issue here. Have you found a solution?

**Comment by plasticrake** [comment]
@dephanixk @Eloquite  I'm going to close this issue. Please resubmit a new issue and please make sure to fill out the issue template including homebridge log output. I can't help without more info.
