### ISSUE TITLE
TP Link LB110 bulb appears twice when adding to Home

### ISSUE THREAD

**Issue by UNiXMIT** [plasticrake/homebridge-tplink-smarthome#58]
I have the LB110 bulb and it works fine but when adding it to Home app on iOS it appears twice. One makes the light fade on/off the other makes it turn on/off instantly. Is this supposed to happen? It's not a major issue as I just only favourite one of them but it is odd.
Thanks

unix@unix:$ node -v
v7.10.0
unix@unix:$ homebridge -v
0.4.38
unix@unix:$ cat /etc/debian_version
9.1

    "platforms": [{
           "platform": "TplinkSmarthome",
           "name": "TplinkSmarthome"
    }]

**Comment by plasticrake** [comment]
Please provide the homebridge output or log file. Also are you running any other plugins? Both devices you see are associated with the same homebridge instance?

**Comment by UNiXMIT** [comment]
I will post the log here as soon as possible. There’s only one instance of homebridge running and both devices are connected to the same instance. I aren’t running any other plugins. I was running homebridge-hs100 and the exact same thing happened there which made me think it was expected behaviour of tp link bulb.

**Comment by UNiXMIT** [comment]
Well the output when I start Homebridge doesn't show 2 separate bulbs but it shows as 2 bulbs, in the Home app, that do the same thing essentially. Is there a higher log level I can set?

Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [TplinkSmarthome] New Device Online: [Study1] plug [8006042B0CE06D80A40DF64B943A6D74197A179E] 10.0.0.13 9999
Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [TplinkSmarthome] Adding: [Study1] plug [8006042B0CE06D80A40DF64B943A6D74197A179E]
Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [TplinkSmarthome] New Device Online: [Lounge1] bulb [80128B321F65E41A0E31CB1F2A6E1859185AD76F] 10.0.0.12 9999
Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [TplinkSmarthome] Adding: [Lounge1] bulb [80128B321F65E41A0E31CB1F2A6E1859185AD76F]
Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [homebridge-tplink-lightbulb.TplinkLightbulb] Lightbulb online: Lounge1 [80128B321F65E41A0E31CB1F2A6E1859185AD76F]
Apr 11 09:05:31 unix homebridge[22980]: [4/11/2018, 9:05:31 AM] [homebridge-tplink-lightbulb.TplinkLightbulb] Configuring: Lounge1

**Comment by UNiXMIT** [comment]
For some reason homebridge-tplink-lightbulb@1.1.1 wasn't uninstalled fully and even though I removed the config for this it was still working. Removed it fully and it's fine now. Thanks
