### ISSUE TITLE
LB100 support

### ISSUE THREAD

**Issue by sjzasada** [plasticrake/homebridge-tplink-smarthome#6]
Thanks for a great plugin. Are the LB100 range of lightbulbs supported, or are there plans to do so?

**Comment by jeffdoll-wf** [comment]
HS200 switches are supported by this. This leads me to believe that all tp-link platform devices currently available will work.

**Comment by pauloruberto** [comment]
@jeffdoll-wf Thanks for posting about the HS200's I just ordered a couple and was looking around for a homebridge plugin!

**Comment by uberadminer** [comment]
This would be great to see, shouldnt be too hard either

**Comment by plasticrake** [comment]
Hi! I have added support for lightbulbs for real! I still don't have any to test, but I wrote a device simulator https://github.com/plasticrake/tplink-smarthome-simulator and I hope its working! If anyone could test and let me know that would be great! Make sure to add to your config:
```json
"deviceTypes": ["plug","bulb"]

**Comment by plasticrake** [comment]
Lightbulb support should be pretty decent now. I have an LB130 to test with
