### ISSUE TITLE
ENHANCEMENT: Support for 3 way switches HS210

### ISSUE THREAD

**Issue by Midifreakz** [plasticrake/homebridge-tplink-smarthome#60]
### Versions

- **Node**:       `node --version`
- **Homebridge**: `homebridge --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

I tried to fill in the form as good as possible but the form is not designed for product sugestions.
I just wanted to reach out to the developers of this plugin and apply for beta testing if this feature would get added. 

Hope that anyone else is looking for a solution to get 3 way switches working inside the homekit app.

TP link is the only manufacturer that offers 3 way switches for the moment.

**Comment by timcharper** [comment]
I have 5 3-way switches installed, and they work perfectly with this plugin. Although... I only have one smart switch per 3-way circuit :D. Because I'm cheap like that? And pairing with a dumb switch is the only option when dealing with 4-way switches.

I think the only reason why it says they aren't supported is because it doesn't automatically detect two switches in a group and therefore only send the on / off signal to one or the other? ¯\_(ツ)_/¯

**Comment by timcharper** [comment]
> apply for beta testing

No need to apply! Git clone, npm pack, upload to pi and install tgz file!

**Comment by Goobaroo** [comment]
I just installed some of the HS210 kits.  And came up with this solution.

I figured out which of the two was the main switch and which was the dummy in the Home app.

These lights are for my Front Hall, so I renamed the one that worked _FH Live_ and the other _FH Dummy_ then grouped them as simply _Front Hall_.  

Now I just have the one device listed and all the commands work fine calling it Front Hall.

Hope that's of help for you @Midifreakz

**Comment by plasticrake** [comment]
Can someone confirm if HS210 switch are working as expected? I don't have any myself to test.

**Comment by timcharper** [comment]
@plasticrake I have several HS210's, although I only have one smart switch installed per light (with a handful of dumb 3-way or 4-way switches). They all work fine.

**Comment by plasticrake** [comment]
I'm going to close this as it appears to be working fine? If not please reopen a new issue and I'll see if I can improve support for this.
