### ISSUE TITLE
Support for Smart Dimmer Switch HS220

### ISSUE THREAD

**Issue by Indochild56** [plasticrake/homebridge-tplink-smarthome#61]
Any plans to add support for this?

**Comment by Indochild56** [comment]
So I found out that it still shows up in the home app just without the dimmer function.

**Comment by timcharper** [comment]
Support here should be really simple once support lands in https://github.com/plasticrake/tplink-smarthome-api

See https://github.com/plasticrake/tplink-smarthome-api/issues/49

**Comment by plasticrake** [comment]
@Indochild56 @timcharper I'm still waiting for someone with an HS220 device to figure out the commands. Once someone does that I can add support!

**Comment by Lamthesheep** [comment]
@misterd4n @plasticrake 
Same. Please let me know how I can help

**Comment by timcharper** [comment]
I just ordered one, too :) Thanks to cyber-monday deal. I have an open-wrt router, I should be able to use tcpdump to figure it out.

**Comment by plasticrake** [comment]
Awesome! Yeah if anyone can provide the commands I can add support.

**Comment by IceCreamSheep** [comment]
> As seen in the other thread, done and done :)

Hey Tim, hate to sound stupid here, but which thread are you referencing?

**Comment by timcharper** [comment]
https://github.com/plasticrake/tplink-smarthome-api/issues/49

**Comment by vfour** [comment]
Let me know if you need any beta testers on this one.

**Comment by DaveGut** [comment]
Just saw this (sorry for the lateness).  Have HS220 basic commands in SmartThings and Hubitat where a user verified functionality.  For basic dimming, first turn on the device, then send the level command:

{"smartlife.iot.dimmer" :{"set_brightness" :{"brightness" :**_${percentage}_**}}}

**Comment by plasticrake** [comment]
To the HS200, HS210, HS220 owners: I'm thinking of exposing these devices as a lightbulb instead of an outlet. What do you all think? At a minimum I may expose HS220 as a lightbulb since it supports brightness.

I assume these are primarily used to control lights right? Anybody using them for non-lights?


```
Service.Outlet = function(displayName, subtype) {
  Service.call(this, displayName, '00000047-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);
  this.addCharacteristic(Characteristic.OutletInUse);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
};
```

```
Service.Lightbulb = function(displayName, subtype) {
  Service.call(this, displayName, '00000043-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Brightness);
  this.addOptionalCharacteristic(Characteristic.Hue);
  this.addOptionalCharacteristic(Characteristic.Saturation);
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.ColorTemperature); //Manual fix to add temperature
};
```

**Comment by vfour** [comment]
I agree.  Using this for anything other than a light would be the exception (for example, a fan).   Most would use these with dimmable light bulbs.

**Comment by autopear** [comment]
Usually this dimmer switch does not have the capable power to supply a ceiling fan, it should only be used to control lights.

**Comment by davidjgonzalez** [comment]
Only used for lights

**Comment by davidjgonzalez** [comment]
Is there a target version that will have the HS220 dimmer support?

**Comment by plasticrake** [comment]
I just cut a new release (v4.0.0) with this functionality. It required a very large refactoring and rewrite of the code, so hopefully it didn't break anything. (#80) 

It will add HS220 switches as Lightbulbs in HomeKit, which should allow you to control the brightness. I believe it should remove the existing Outlet that was previously created and seamlessly add the Lightbulb.

I do not have an HS220 myself, so let me know how its working. There also may be some weirdness around adjusting brightness while its off, etc. So please test to make sure its working as expected.

**Comment by autopear** [comment]
Adjusting the brightness while off will turn the lights on. You cannot set brightness while the lights are off in Kasa app as well.

Everything seems to be working fine, except one thing: when you set the brightness from some positive value to 0%, it turns off the lights correctly, but in the log I found the following exception:

`[TplinkSmarthome] { ResponseError: err_code not zero response: {"err_code":-3,"err_msg":"invalid argument"} command: {"smartlife.iot.dimmer":{"set_brightness":{"brightness":0}}}
    at processResponse (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/device/index.js:509:11)
    at /usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/device/index.js:274:23
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/device/index.js:3:103)
    at _next (/usr/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/device/index.js:5:194)
  name: 'ResponseError',
  response: { err_code: -3, err_msg: 'invalid argument' },
  command: { 'smartlife.iot.dimmer': { set_brightness: [Object] } },
  errorModules: 'smartlife.iot.dimmer' }`

**Comment by vfour** [comment]
Works great for me!  Thank you @plasticrake !

**Comment by Austinthemighty** [comment]
Works fine for me, Thanks

**Comment by davidjgonzalez** [comment]
Do I have to delete my cache an/or persist folders (and re-add homebridge?) should I include/exclude HS210 from config.jsons switchModels?

im on homebridge-tplink-smarthome 4.0.1
