### ISSUE TITLE
Possible to deley switch on/off for HS110?

### ISSUE THREAD

**Issue by maisun** [plasticrake/homebridge-tplink-smarthome#73]
Hi,
Thanks for the great HB plugin, it works very well for the past year :)
Question: would it be possible to add an option to delay execution of switch on/off command for HS110?
HK doesn't seem to allow delays in scenes and automation - I'd like to delay turning on video camera by 10 minutes when the alarm system is switched on.
Thank you in advance!

**Comment by plasticrake** [comment]
Homekit unfortunately does not allow you to create ad-hoc schedules like that. You can use the underlying tplink-smarthome-api to create a Kasa schedule to turn on/off after a period of time, but that is outside the scope of this plugin.
