### ISSUE TITLE
Outdoor plug KP400 works fine

### ISSUE THREAD

**Issue by cuellarfr** [plasticrake/homebridge-tplink-smarthome#85]
Not an issue, just a heads up so you can update the readme file. I just tried the plugin with the new outdoor plug KP400 and it works great. Characteristics are 'on', and 'OutletInUse'. Both outlets can be operated individually.

**Comment by ronaldfarber** [comment]
@cuellarfr I'm thinking about buying the KP400 but I don't have any other TP-Link products so I'm unfamiliar with the setup of accessories. Did you have to do anything special to add the accessory? Or did you just set it up based on IP/MAC address? Thanks for any help!

**Comment by cuellarfr** [comment]
No, I didn’t have to do anything special. If you already use homebridge,
install this plugin using the standard config and the new plugs will show
up in the home app.

**Comment by ronaldfarber** [comment]
Thanks for the help! I didn't realize it would auto-detect them on the network. I just setup my KP400 and can confirm it works great!

**Comment by plasticrake** [comment]
Thanks!
