### ISSUE TITLE
HS103 working as expected

### ISSUE THREAD

**Issue by oceanapplications** [plasticrake/homebridge-tplink-smarthome#94]
### Expected Behavior
Device Working
### Current Behavior
Device Works

### Versions
- **Node**:   v10.16.0   `node --version`
- **Homebridge**: 0.4.50 `homebridge --version`
- **OS**:      HOOBS 2.1

### Configuration
```json
     {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome"
      }
```

**Comment by plasticrake** [comment]
Thanks!
